export type FormVariantId =
  | 'HEALTH_RECORD_ADD'
  | 'HEALTH_RECORD_EDIT'
  | 'ALLERGY_EDIT'
  | 'FOOD_PLAN_ADD'
  | 'STERILIZATION_ADD'
  | 'CONSULTATION_ADD'
  | 'DEWORMER_ADD'
  | 'VACCINE_ADD'
  | 'WEIGHING_ADD'
  | 'HEART_RATE_ADD'
  | 'RESPIRATORY_RATE_ADD'
  | 'DOCUMENT_ADD';


