# docker/Dockerfile.staging

# Step 1
FROM node:20-alpine AS build
WORKDIR /app
COPY ../package*.json ./
RUN npm ci
COPY ../ ./
RUN npm run build -- --configuration=staging

# Step 2
FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist/jokeur_frontend ./

EXPOSE 4000

CMD ["node", "dist/jokeur_frontend/server/server.mjs"]
